backend:
  name: git-gateway
  branch: main
  
local_backend: true

media_folder: 'static/images/uploads'
public_folder: 'images/uploads'

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Landing"
        name: "landing"
        file: "src/lib/content/landing.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Our Products Title , name: our_products_title , widget: string}
