backend:
  name: github
  repo: espoleta-tec/web-v4
  branch: main
  
local_backend: true

media_folder: 'static/images/uploads'
public_folder: 'images/uploads'

media_library:
  name: cloudinary
  config:
    cloud_name: lazaroofarrill
    api_key: 476522667641615

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Landing"
        name: "landing"
        file: "src/lib/content/landing.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Our Products Title , name: our_products_title , widget: string}
          - {label: 'Header Image', name: 'header_image', widget: image}
