backend:
  name: git-gateway
  branch: main

local_backend: true

extension: json

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: single_file

  # Required - a list of locales to show in the editor UI
  locales: [en, es]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

media_folder: 'static/images/uploads'
public_folder: 'images/uploads'

media_library:
  name: cloudinary
  config:
    cloud_name: lazaroofarrill
    api_key: 476522667641615

collections:
  - label: 'Pages'
    name: 'pages'
    i18n:
      structure: single_file
      locales: [en, es]
    files:
      - label: 'Landing'
        name: 'landing'
        file: 'src/lib/content/landing.json'
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - { label: 'Header Image', name: 'header_image', widget: image }
          - {
              label: Our Products Title,
              name: our_products_title,
              widget: string,
              i18n: true
            }
          - {
              label: Our Products Body,
              name: our_products_body,
              widget: text,
              i18n: true
            }
          - {
              label: Our Clients,
              name: our_clients,
              widget: string,
              i18n: true
            }
          - {
              label: Features Title,
              name: station_features,
              widget: string,
              i18n: true
            }
          - {
              label: Features Body,
              name: station_features_body,
              widget: string,
              i18n: true
            }
      - label: About Us
        name: about_us
        file: src/lib/content/about_us.json
        i18n: true
        fields:
          - label: Obout the company
            name: about_the_company
            i18n: true
            widget: object
            fields:
              - { label: Title, name: title, i18n: true, widget: string }
              - label: Company points
                name: company_points
                widget: list
                i18n: true
                fields:
                  - {
                      label: Title,
                      name: point_title,
                      widget: string,
                      i18n: true
                    }
                  - { label: Body, name: point_body, widget: text, i18n: true }
              - {
                  label: The Team Title,
                  name: the_team_title,
                  widget: string,
                  i18n: true
                }
              - {
                  label: The Team Body,
                  name: the_team_body,
                  widget: text,
                  i18n: true
                }

  - label: Team Member
    name: team_members
    folder: 'src/lib/content/team_members'
    extension: json
    create: true
    identifier_field: name
    i18n: true
    fields:
      - { label: 'Name', name: 'name', widget: string }
      - { label: 'Description', name: 'description', widget: text, i18n: true }
      - { label: 'Photo', name: 'photo', widget: image }
